version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Corretto 17"

  pre_build:
    commands:
      - echo "Commit $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - mvn -P web -B -q clean test

  build:
    commands:
      - echo "Building WEB JAR (profile=web) -> target/app.jar"
      - mvn -P web -B -q clean package -DskipTests
      - if [ -f target/app.jar ]; then cp target/app.jar app.jar; else echo 'ERROR: target/app.jar not found'; exit 1; fi

      - echo "Building CLI JAR (VG)"
      - mvn -P cli -B -q package
      - if [ -n "$ARTIFACTS_BUCKET" ]; then CLI_JAR=$(ls -1 target/*.jar | grep -v original | grep -v app.jar | head -n1 || true); if [ -n "$CLI_JAR" ]; then echo "Uploading VG CLI jar to s3://$ARTIFACTS_BUCKET/builds/"; aws s3 cp "$CLI_JAR" "s3://$ARTIFACTS_BUCKET/builds/s3-cli-${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}.jar"; else echo "No CLI jar found under target/; skipping upload"; fi; else echo "ARTIFACTS_BUCKET not set; skip VG upload"; fi

artifacts:
  files:
    - Procfile
    - app.jar
  discard-paths: yes
