version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - 'echo "Commit $CODEBUILD_RESOLVED_SOURCE_VERSION"'
      - 'mvn -P web -B -q clean test'

  build:
    commands:
      - 'echo "Building WEB JAR (profile=web)"'
      - 'mvn -P web -B -q package'
      - 'WEB_JAR=$(ls -1 target/*.jar | head -n1)'
      - 'cp "$WEB_JAR" target/webapp.jar'
      - 'echo "Building CLI JAR (VG)"'
      - 'mvn -B -q -DskipTests=false package'

  post_build:
    commands:
      - mkdir -p artifact
      - BOOT_JAR=$(ls -1 target/*.jar | grep -v original | head -n1)
      - cp "$BOOT_JAR" artifact/app.jar
  artifacts:
    files:
      - Procfile
      - artifact/app.jar
    discard-paths: yes

