version: 0.2

phases:
  pre_build:
    commands:
      - echo "Commit $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - mvn -B -q -DskipTests=false test
  build:
    commands:
      - mvn -B -q -DskipTests=false package
  post_build:
    commands:
      - COMMIT="${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}"
      - mkdir -p artifact
      - cp target/*-with-dependencies*.jar artifact/s3-cli-$COMMIT.jar || true
      - if [ ! -f artifact/s3-cli-$COMMIT.jar ]; then cp target/*.jar artifact/s3-cli-$COMMIT.jar; fi
      - aws s3 cp artifact/s3-cli-$COMMIT.jar s3://$ARTIFACTS_BUCKET/builds/

artifacts:
  files:
    - artifact/**/*
  discard-paths: yes
