version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - 'echo "Using Corretto 17"'

  pre_build:
    commands:
      - 'echo "Commit $CODEBUILD_RESOLVED_SOURCE_VERSION"'
      - 'mvn -P web -B -q clean test'

  build:
    commands:
      - 'set -e'
      - 'echo "Building WEB JAR (profile=web) -> target/app.jar"'
      - 'mvn -P web -B -q clean package -DskipTests'
      - 'test -f target/app.jar'
      - 'cp target/app.jar app.jar'

      - 'echo "Building CLI JAR (VG)"'
      - 'mvn -P cli -B -q package'
      - '[ -n "$ARTIFACTS_BUCKET" ] || { echo "ARTIFACTS_BUCKET not set; skip VG upload"; exit 0; }'
      - 'CLI_JAR=$(ls -1 target/*.jar | grep -v original | grep -v app.jar | head -n1 || true)'
      - '[ -n "$CLI_JAR" ] && echo "Uploading $CLI_JAR to s3://$ARTIFACTS_BUCKET/builds/s3-cli-${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}.jar" && aws s3 cp "$CLI_JAR" "s3://$ARTIFACTS_BUCKET/builds/s3-cli-${CODEBUILD_RESOLVED_SOURCE_VERSION:-local}.jar" || echo "No CLI jar found; skipping upload"'

artifacts:
  files:
    - Procfile
    - app.jar
  discard-paths: yes
